#!/usr/bin/env python3
"""Validate the paper catalog and generate its README and static website views."""

from __future__ import annotations

import argparse
import base64
import json
import re
import sys
from collections import Counter
from datetime import date, timedelta
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
PAPERS_PATH = ROOT / "data" / "papers.json"
CHAPTERS_PATH = ROOT / "data" / "chapters.json"
CATALOG_PATH = ROOT / "data" / "catalog.json"
README_PATH = ROOT / "README.md"
SITE_DIR = ROOT / "site"
DIST_PATH = ROOT / "dist" / "index.html"
START_MARKER = "<!-- catalog:start -->"
END_MARKER = "<!-- catalog:end -->"


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def load_catalog() -> tuple[list[dict], list[dict], dict]:
    papers = load_json(PAPERS_PATH)
    chapters = load_json(CHAPTERS_PATH)
    catalog = load_json(CATALOG_PATH)
    validate(papers, chapters, catalog)
    return papers, chapters, catalog


def validate(papers: list[dict], chapters: list[dict], catalog: dict) -> None:
    errors: list[str] = []
    chapter_keys = [chapter.get("key") for chapter in chapters]
    if len(chapter_keys) != 9 or len(set(chapter_keys)) != len(chapter_keys):
        errors.append("chapters.json must contain nine unique chapter keys")

    try:
        date.fromisoformat(catalog["generated_at"])
    except (KeyError, TypeError, ValueError):
        errors.append("catalog.generated_at must be an ISO date")
    if not isinstance(catalog.get("recent_days"), int) or catalog.get("recent_days", 0) < 1:
        errors.append("catalog.recent_days must be a positive integer")

    ids: set[str] = set()
    arxiv_ids: set[str] = set()
    for index, paper in enumerate(papers):
        label = paper.get("id") or f"row {index + 1}"
        if not paper.get("id") or paper["id"] in ids:
            errors.append(f"duplicate or missing paper id: {label}")
        ids.add(paper.get("id", ""))
        if not paper.get("title"):
            errors.append(f"missing title: {label}")
        if paper.get("chapter") not in chapter_keys:
            errors.append(f"unknown chapter for {label}: {paper.get('chapter')}")
        if not paper.get("paper_url") and not paper.get("code_url"):
            errors.append(f"missing public URL: {label}")
        for field in ("paper_url", "code_url"):
            value = paper.get(field)
            if value and not value.startswith("https://"):
                errors.append(f"{field} must use https for {label}")
        try:
            date.fromisoformat(paper["added_at"])
        except (KeyError, TypeError, ValueError):
            errors.append(f"invalid added_at for {label}")
        published = paper.get("published_at")
        if published and not re.fullmatch(r"\d{4}-\d{2}(?:-\d{2})?", published):
            errors.append(f"invalid published_at for {label}: {published}")
        arxiv_id = paper.get("arxiv_id")
        if arxiv_id:
            if arxiv_id in arxiv_ids:
                errors.append(f"duplicate arXiv id: {arxiv_id}")
            arxiv_ids.add(arxiv_id)

    if errors:
        raise ValueError("Catalog validation failed:\n- " + "\n- ".join(errors))


def recent_papers(papers: list[dict], catalog: dict) -> list[dict]:
    snapshot = date.fromisoformat(catalog["generated_at"])
    earliest = snapshot - timedelta(days=catalog["recent_days"] - 1)
    return sorted(
        (paper for paper in papers if earliest <= date.fromisoformat(paper["added_at"]) <= snapshot),
        key=lambda paper: (paper["added_at"], paper["title"].casefold()),
        reverse=True,
    )


def md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def md_links(paper: dict) -> str:
    links = []
    if paper.get("paper_url"):
        links.append(f"[Paper]({paper['paper_url']})")
    if paper.get("code_url") and paper["code_url"] != paper.get("paper_url"):
        links.append(f"[Code]({paper['code_url']})")
    return " · ".join(links)


def readme_block(papers: list[dict], chapters: list[dict], catalog: dict) -> str:
    chapter_by_key = {chapter["key"]: chapter for chapter in chapters}
    recent = recent_papers(papers, catalog)[:20]
    window = catalog["recent_days"]
    site_url = catalog["site_url"]
    lines = [
        START_MARKER,
        "<!-- Generated by scripts/catalog.py. Edit data/*.json instead of this block. -->",
        "## Latest additions",
        "",
        f"The catalog snapshot is **{catalog['generated_at']}**. This section shows up to 20 papers added in the past **{window} days**.",
        "",
    ]
    if recent:
        lines.extend(["| Added | Paper | Survey chapter | Links |", "|:-:|:-|:-|:-:|"])
        for paper in recent:
            chapter = chapter_by_key[paper["chapter"]]
            chapter_url = f"{site_url}?chapter={quote(chapter['key'])}#papers"
            lines.append(
                f"| {paper['added_at']} | {md_cell(paper['title'])} | "
                f"[{md_cell(chapter['title'])}]({chapter_url}) | {md_links(paper)} |"
            )
    else:
        lines.append(f"_No papers were added during this {window}-day window._")

    counts = Counter(paper["chapter"] for paper in papers)
    lines.extend(
        [
            "",
            "## Browse the collection",
            "",
            f"The complete collection contains **{len(papers)} papers** organized around the survey's nine chapters.",
            "",
            "| Survey chapter | Scope | Papers |",
            "|:-|:-|--:|",
        ]
    )
    for chapter in chapters:
        chapter_url = f"{site_url}?chapter={quote(chapter['key'])}#papers"
        lines.append(
            f"| [{md_cell(chapter['title'])}]({chapter_url}) | "
            f"{md_cell(chapter['description'])} | {counts[chapter['key']]} |"
        )
    lines.extend(
        [
            "",
            f"**[Search and filter all {len(papers)} papers on the project website →]({site_url}#papers)**",
            "",
            "Paper metadata is maintained in [`data/papers.json`](data/papers.json). To suggest a missing work, open a pull request with its public paper link and the most relevant survey chapter.",
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def rendered_readme(papers: list[dict], chapters: list[dict], catalog: dict) -> str:
    current = README_PATH.read_text(encoding="utf-8")
    if START_MARKER not in current or END_MARKER not in current:
        raise ValueError("README catalog markers are missing")
    before, rest = current.split(START_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return before.rstrip() + "\n\n" + readme_block(papers, chapters, catalog) + after


def data_uri(path: Path) -> str:
    media_type = "image/png" if path.suffix.lower() == ".png" else "application/octet-stream"
    payload = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{media_type};base64,{payload}"


def rendered_site(papers: list[dict], chapters: list[dict], catalog: dict) -> str:
    template = (SITE_DIR / "index.html").read_text(encoding="utf-8")
    css = (SITE_DIR / "styles.css").read_text(encoding="utf-8")
    app = (SITE_DIR / "app.js").read_text(encoding="utf-8")
    payload = json.dumps(
        {"papers": papers, "chapters": chapters, "meta": catalog},
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    replacements = {
        "/* __INLINE_CSS__ */": css,
        "/* __INLINE_DATA__ */": f"window.CATALOG={payload};",
        "/* __INLINE_APP__ */": app,
        "__CHAPTER_FIGURE_DATA_URI__": data_uri(ROOT / "figs" / "chapters.png"),
    }
    for marker, value in replacements.items():
        if marker not in template:
            raise ValueError(f"Missing site template marker: {marker}")
        template = template.replace(marker, value)
    return template


def check_site(html: str) -> None:
    forbidden = ["box-shadow", "text-shadow", "drop-shadow", "linear-gradient", "radial-gradient"]
    failures = [token for token in forbidden if token in html]
    if "__INLINE_" in html or "__CHAPTER_FIGURE_DATA_URI__" in html:
        failures.append("unresolved template marker")
    if '<link rel="stylesheet"' in html or '<script src=' in html:
        failures.append("external CSS or JavaScript")
    if failures:
        raise ValueError("Generated site check failed: " + ", ".join(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("render-readme", "build-site", "check", "all"))
    args = parser.parse_args()
    papers, chapters, catalog = load_catalog()

    expected_readme = rendered_readme(papers, chapters, catalog)
    site = rendered_site(papers, chapters, catalog)
    check_site(site)

    if args.command in ("render-readme", "all"):
        README_PATH.write_text(expected_readme, encoding="utf-8")
        print(f"Rendered README catalog view for {len(papers)} papers")
    if args.command in ("build-site", "all"):
        DIST_PATH.parent.mkdir(parents=True, exist_ok=True)
        DIST_PATH.write_text(site, encoding="utf-8")
        print(f"Built self-contained site at {DIST_PATH}")
    if args.command == "check":
        if README_PATH.read_text(encoding="utf-8") != expected_readme:
            print("README catalog view is stale; run: python3 scripts/catalog.py render-readme", file=sys.stderr)
            return 1
        print(f"Catalog, README, and site validated ({len(papers)} papers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
